# Site settings
title: An example home page
description: An example home page
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://deangodfree.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dean Godfree
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: DevOps Coach
email: deangodfree@gmail.com
twitter_username: deangodfree
github_username:  DeanGodfree
gplus_username:  deangodfree

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
